name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        POSTGRES_USER: POSTGRES
        POSTGRES_PASSWORD: POSTGRES
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test PG
      run: cd ./Back/QuestionsList/QuestionsList.Infrastructure && bash ./intialize_postgres.sh



